import { test, expect } from '@playwright/test'

test('group toggles retain edits, append once, and keep bottom controls visible', async ({page}) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await page.goto('/?preview=1')
  await page.getByRole('button', {name: 'Load examples'}).click()
  await expect(page.getByRole('heading', {name: 'AI PDF Reader'})).toBeVisible()
  await expect(page.getByRole('tab')).toHaveCount(0)
  await expect(page.locator('.sidebar, .document-table')).toHaveCount(0)
  const firstName = page.getByLabel('Claimant Information / First Name', {exact: true})
  await expect(firstName).toHaveValue('Avery')
  await firstName.fill('Avery edited')
  const settings = page.getByRole('button', {name: 'Settings', exact: true})
  await settings.click()
  await expect(page.getByRole('region', {name: 'Settings group'})).toBeInViewport()
  await page.getByLabel('AWS region').fill('us-west-2')
  await page.getByLabel('Bedrock API key').fill('synthetic-test-key')
  await settings.click()
  await expect(page.locator('#group-Settings')).toBeHidden()
  await settings.click()
  await expect(page.locator('#group-Settings')).toHaveCount(1)
  await expect(page.getByLabel('AWS region')).toHaveValue('us-west-2')
  await expect(page.getByLabel('Bedrock API key')).toHaveValue('synthetic-test-key')
  await expect(firstName).toHaveValue('Avery edited')
  await page.getByRole('button', {name: 'Output', exact: true}).click()
  await expect(page.getByRole('region', {name: 'Output group'})).toBeInViewport()
  expect(await page.locator('.extra-group').evaluateAll(groups => groups.map(g => g.id))).toEqual(['group-Settings', 'group-Output'])
  await page.getByRole('button', {name: 'Fields', exact: true}).click()
  await expect(firstName).toBeInViewport()
  await page.getByRole('button', {name: 'Save field changes (1)'}).click()
  await expect(page.getByRole('button', {name: 'Save field changes', exact: true})).toBeDisabled()
  await expect(firstName).toHaveValue('Avery edited')
  await expect(page.getByLabel('Processing progress')).toHaveAttribute('value', '2')
  await page.screenshot({path: '../test-results/compact-form-480x900.png'})
  for (const height of [561, 861, 1061]) {
    await page.setViewportSize({width: 464, height})
    await page.getByRole('button', {name: 'Settings', exact: true}).click()
    await expect(page.getByRole('navigation', {name: 'Form navigation'})).toBeInViewport({ratio: 1})
    await expect(page.getByRole('button', {name: 'Save field changes', exact: true})).toBeInViewport({ratio: 1})
    await expect(page.getByLabel('Processing progress')).toBeInViewport({ratio: 1})
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBeTruthy()
    expect(await page.locator('main').evaluate(el => el.scrollWidth <= el.clientWidth)).toBeTruthy()
  }
  await page.setViewportSize({width: 464, height: 561})
  await page.getByRole('button', {name: 'Fields', exact: true}).click()
  await page.screenshot({path: '../test-results/compact-form-480x600.png'})
  expect(errors).toEqual([])
})

test('document selection, validation edits, PDF navigation, and settings errors', async ({page}) => {
  await page.goto('/?preview=1')
  await page.getByRole('button', {name: 'Load examples'}).click()
  await page.getByLabel('Current document').selectOption('example-2')
  await expect(page.getByText('NEXT STEP: Failed', {exact: true})).toBeVisible()
  await page.getByLabel('Claimant Information / Customer Name', {exact: true}).fill('Reviewed Example Customer')
  await page.getByRole('button', {name: 'Save field changes (1)'}).click()
  await expect(page.getByText('NEXT STEP: Passed', {exact: true})).toBeVisible()
  await page.getByRole('button', {name: 'Documents', exact: true}).click()
  await page.getByLabel('Search documents').fill('Morgan')
  await expect(page.locator('.document-item')).toHaveCount(1)
  await page.locator('.document-name').filter({hasText: 'MORGAN,AVERY.pdf'}).click()
  await page.getByRole('button', {name: 'PDF', exact: true}).click()
  await expect(page.getByAltText('Page 1 of MORGAN,AVERY.pdf')).toBeVisible()
  await page.getByRole('button', {name: 'Next page', exact: true}).click()
  await expect(page.getByAltText('Page 2 of MORGAN,AVERY.pdf')).toBeVisible()
  await page.getByRole('button', {name: 'Zoom in', exact: true}).click()
  await expect(page.getByRole('button', {name: 'Reset zoom'})).toHaveText('125%')
  await page.getByRole('button', {name: 'PDF', exact: true}).click()
  await page.getByRole('button', {name: 'PDF', exact: true}).click()
  await expect(page.getByRole('button', {name: 'Reset zoom'})).toHaveText('125%')
  await page.getByRole('button', {name: 'Settings', exact: true}).click()
  await expect(page.getByLabel('Output token budget')).toHaveValue('16384')
  await page.getByRole('button', {name: 'Test connection'}).click()
  await expect(page.getByRole('alert')).toContainText('only in the Python desktop app')
})

test('native bridge initialization and real queue progress semantics', async ({page}) => {
  await page.addInitScript(() => {
    const fixture = {documents: [], busy: true, stage: 'Extracting synthetic document', bedrock: 'Connected', elapsed: 4,
      progress: {done: 1, total: 3}, key_configured: true, output_directory: 'Synthetic output',
      settings: {region: 'us-east-2', model: 'test', max_tokens: 16384, temperature: 0, document_limit: 100000}}
    Object.assign(window, {queueFixture: fixture})
    setTimeout(() => {
      window.pywebview = {api: {get_state: async () => ({ok: true, value: structuredClone(fixture)})}}
      window.dispatchEvent(new Event('pywebviewready'))
    }, 150)
  })
  await page.goto('/')
  const bar = page.getByLabel('Processing progress')
  await expect(bar).toHaveAttribute('value', '1')
  await expect(bar).toHaveAttribute('max', '3')
  await page.evaluate(() => Object.assign((window as unknown as {queueFixture: object}).queueFixture, {stage: 'Checking missing addresses: synthetic.pdf'}))
  await expect(bar).not.toHaveAttribute('value')
  await expect(page.locator('.progress-indicator')).toBeVisible()
  await page.evaluate(() => Object.assign((window as unknown as {queueFixture: object}).queueFixture, {busy: false, stage: 'Queue finished', progress: {done: 3, total: 3}}))
  await expect(bar).toHaveAttribute('value', '3')
  await expect(page.getByRole('button', {name: 'Open', exact: true})).toBeEnabled()
  await expect(page.getByText('Synthetic preview · no Bedrock calls')).toHaveCount(0)
})
